### ISSUE TITLE
Return unexpected result by using atomic increment 

### ISSUE THREAD

**Issue by xosdy** [edragonconnect/ecto_tablestore#18] opened 2021-02-04 03:52 UTC
## Table Schema
```elixir
tablestore_schema "test_ots" do
  field :id, :id, primary_key: true
  field :num1, :integer
  field :num2, :integer
end
```

## Steps to Reproduce
```elixir
{:ok, x} = Repo.insert(%TestOTS{id: 0, num1: 0, num2: 0}, condition: condition(:ignore))

x
|> change(num1: {:increment, 1})
|> Repo.update(condition: condition(:expect_exist))
```

## Expected Behavior
```elixir
{:ok,
 %TestOTS{
   __meta__: #Ecto.Schema.Metadata<:loaded, "test_ots">,
   id: 0,
   num1: 1,
   num2: 0
 }}
```

## Current Behavior
```elixir
{:ok,
 %TestOTS{
   __meta__: #Ecto.Schema.Metadata<:loaded, "test_ots">,
   id: 0,
   num1: {:increment, 1},
   num2: 1
 }}
```

## Environment
- Elixir 1.11.3
- OTP 23
- ecto_tablestore 13ff7c8

**Comment by xinz** [comment] 2021-02-04 14:54
Thanks very much!

Let's take the reproduction step as an example:

```
{:ok, x} = Repo.insert(%TestOTS{id: 0, num1: 0, num2: 0}, condition: condition(:ignore))

x
|> change(num1: {:increment, 1})
|> Repo.update(condition: condition(:expect_exist))
```

After the fixed, we need to explicitly input the `returning` option like this:

```
x
|> change(num1: {:increment, 1})
|> Repo.update(condition: condition(:expect_exist), returning: [:num1])
```

If there are more fields in changes, like this:

```
x
|> change(num1: {:increment, 1}, num2: -1, other_field_change: non_atomic_increment)
|> Repo.update(condition: condition(:expect_exist), returning: [:num1])
```

Still need to explicitly input `returning: [:num1]` for the atomic increment field, but the setting of `:num2` and `:other_field_change` fields are optional, the changed fields will be merged into the successful result of the `Repo.update/2`.

When more `:increment` operations like this:

```
x
|> change(num1: {:increment, 1}, num2: {:increment, 1})
|> Repo.update(condition: condition(:expect_exist), returning: [:num1, :num2])
```

Both `:num1` and `:num2` are required be set into `returning` in any order.

Note: since tablestore does not support to return changed fields(attribute columns) from server when insert/update, except the atomic increment operation can return the final incremented value(return as `:RT_AFTER_MODIFY`) from server.

**Comment by xinz** [comment] 2021-02-04 14:56
WDYT about this proposal?

**Closed as completed** 2021-02-05 09:34 UTC
